// <auto-generated />
using InventoryApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("InventoryApi.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Black",
                            Description = "Smart TV 4K",
                            ManufacturerId = 2,
                            Name = "TV 50 inch",
                            SupplierId = 1,
                            Type = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Color = "White",
                            Description = "Game Console",
                            ManufacturerId = 1,
                            Name = "PlayStation 5",
                            SupplierId = 2,
                            Type = "Electronics"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Pink",
                            Description = "Game Console",
                            ManufacturerId = 5,
                            Name = "Nintendo Switch Lite",
                            SupplierId = 3,
                            Type = "Electronics"
                        });
                });

            modelBuilder.Entity("InventoryApi.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contact")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sony"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Panasonic"
                        },
                        new
                        {
                            Id = 4,
                            Name = "LG"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Nintendo"
                        });
                });

            modelBuilder.Entity("InventoryApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Viewer"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Editor"
                        });
                });

            modelBuilder.Entity("InventoryApi.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contact")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "annv@example.com",
                            Name = "Nguyễn Văn An"
                        },
                        new
                        {
                            Id = 2,
                            Email = "baotran@example.com",
                            Name = "Trần Minh Bảo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lê Thị Bình"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Trần Cường"
                        },
                        new
                        {
                            Id = 5,
                            Contact = "0958237551",
                            Name = "Lý Minh Tuệ"
                        });
                });

            modelBuilder.Entity("InventoryApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Staff 1",
                            PasswordHash = "$2a$12$VMQi9hShzRw3TSxchXXT4ejWyk0T7FAtA1.rRwmib6qm6CUvL6TMm",
                            RoleId = 1,
                            UserName = "staff1"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Manager 1",
                            PasswordHash = "$2a$12$VMQi9hShzRw3TSxchXXT4ejWyk0T7FAtA1.rRwmib6qm6CUvL6TMm",
                            RoleId = 2,
                            UserName = "manager1"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Admin",
                            PasswordHash = "$2a$12$VMQi9hShzRw3TSxchXXT4ejWyk0T7FAtA1.rRwmib6qm6CUvL6TMm",
                            RoleId = 2,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("InventoryApi.Models.Item", b =>
                {
                    b.HasOne("InventoryApi.Models.Manufacturer", "Manufacturer")
                        .WithMany("Items")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryApi.Models.Supplier", "Supplier")
                        .WithMany("Items")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("InventoryApi.Models.User", b =>
                {
                    b.HasOne("InventoryApi.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("InventoryApi.Models.Manufacturer", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("InventoryApi.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("InventoryApi.Models.Supplier", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
